import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/layouts/Providers";
import { Toaster } from "@/components/ui/toaster";
import NavBar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="custom-scrollbar">
            <Script
                strategy="lazyOnload"
                src={`https://www.googletagmanager.com/gtag/js?id=${process.env.GOOGLE_ANALYTICS}`}
            />
            <Script id="ga-script" strategy="lazyOnload">
                {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '${process.env.GOOGLE_ANALYTICS}', {
      page_path: window.location.pathname,
    });
        `}
            </Script>
            <body className={inter.className}>
                <Providers>
                    <nav className="">
                        <NavBar />
                    </nav>
                    {children}
                    <footer>
                        <Footer />
                    </footer>
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
